server:
  port: 80

spring:
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
    path-match:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:file:./database/MetaverseDataBase;auto_server=true;mode=mysql'

  sql:
    init:
      mode: always
      schema-locations:
        - classpath:sql/schema.sql
      platform: sqlite
  jackson:
    default-property-inclusion: non-null
knife4j:
  enable: true
  setting:
    enableFooter: false
mybatis-plus:
  configuration:
    cache-enabled: true